export const DELETE_CAT = 'DELETE_CAT';
export const ADD_CAT = 'ADD_CAT';
export const UPDATE_CAT = 'UPDATE_CAT';
export const TOGGLE_TOASTER = 'TOGGLE_TOASTER';
export const TOASTER_BACK_COLOR = 'TOASTER_BACK_COLOR';
export const TOASTER_MESSAGE = 'TOASTER_MESSAGE';